//
// Created by Glitch on 07/04/2025.
//

#ifndef DININGPHILOSOPHERS_PREVENTDEADLOCK_H
#define DININGPHILOSOPHERS_PREVENTDEADLOCK_H


class PreventDeadLock {

};


#endif //DININGPHILOSOPHERS_PREVENTDEADLOCK_H
