//
// Created by Glitch on 07/04/2025.
//

#ifndef DININGPHILOSOPHERS_PREVENTSTARVATIONDEADLOCK_H
#define DININGPHILOSOPHERS_PREVENTSTARVATIONDEADLOCK_H


class PreventStarvationDeadLock {

};


#endif //DININGPHILOSOPHERS_PREVENTSTARVATIONDEADLOCK_H
